# Generated by Django 6.0 on 2026-02-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.CharField(default='d6fe06f9-a2e4-498f-9e63-219e1fe28c98', max_length=36, primary_key=True, serialize=False),
        ),
    ]
