# Generated by Django 6.0 on 2026-02-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.CharField(default='735b4831-4cdb-4ce0-ac2e-5cdb9f1a2092', max_length=36, primary_key=True, serialize=False),
        ),
    ]
