# Generated by Django 5.2.8 on 2026-02-12 04:36

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.CharField(default=chats.models.generate_uuid, max_length=36, primary_key=True, serialize=False),
        ),
    ]
