# Generated by Django 6.0.1 on 2026-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatName',
            field=models.CharField(default='test_chat', max_length=150),
        ),
    ]
