# Generated by Django 6.0.1 on 2026-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_chatname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_avatar',
            field=models.ImageField(default='avatars/def.jpg', upload_to='avatars/'),
        ),
    ]
